language: ruby
before_install:
  - sudo apt-get update
  - sudo apt-get install wget
  - wget http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-9.27.tar.gz
  - tar -xzf Image-ExifTool-9.27.tar.gz
  - cd Image-ExifTool-9.27
  - perl Makefile.PL
  - make
  - sudo make install
  - exiftool -ver
  - gem install rim json
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
notifications:
  email:
    - janfri26@gmail.com
