language: ruby
before_install:
  - uname -a
  - curl -L http://cpanmin.us | perl - --sudo Image::ExifTool
  - exiftool -ver
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
#  - 3.0
  - ruby-head
  - jruby-head
notifications:
  email:
    - janfri26@gmail.com
