language: ruby
before_install:
  - sudo apt-get install wget
  - wget http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-9.76.tar.gz
  - tar -xzf Image-ExifTool-9.76.tar.gz
  - cd Image-ExifTool-9.76
  - perl Makefile.PL
  - make
  - sudo make install
  - cd ..
  - exiftool -ver
  - gem install rim json test-unit regtest
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - ruby-head
notifications:
  email:
    - janfri26@gmail.com
